doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            gender_enum: App\Infrastructure\Doctrine\Type\GenderEnumType
            role_enum: App\Infrastructure\Doctrine\Type\RoleEnumType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Shared:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Shared/ValueObject'
                prefix: 'App\Domain\Shared\ValueObject'
                alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User/Entity'
                prefix: 'App\Domain\User\Entity'
                alias: App
