refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: POST

login:
    path: /api/login
    methods: POST

method:
    path:       /api/rpc
    controller: App\Application\RpcController::call
    methods: [GET, POST]
