refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: POST

login:
    path: /api/login
    methods: POST

method:
    path:       /api/method/{methodName}
    controller: App\Application\ApiController::method
    methods: [GET, POST]
